name = "graphql-registry"
type = "javascript"

account_id = "1a2a1312f9b14c0611a47d3a511472f7"
workers_dev = true
route = ""
zone_id = ""
target_type = "javascript"
kv_namespaces = [ 
         { binding = "PERSISTED_QUERIES", id = "36784ec0422f41e3a25e6377ea0a4048", preview_id = "36784ec0422f41e3a25e6377ea0a4048" },
         { binding = "SERVICES", id = "9ba3ddd66035413ba8ece7d91cee44a2", preview_id = "9ba3ddd66035413ba8ece7d91cee44a2" }
]
vars = { ENVIRONMENT = "dev" }

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"

[build]
upload.format = "service-worker"
command = "npm run build"