name = "graphql-registry"
type = "javascript"

account_id = "<insert>"
workers_dev = true
route = ""
zone_id = ""
target_type = "javascript"
kv_namespaces = [ 
         { binding = "PERSISTED_QUERIES", id = "<insert>", preview_id = "<insert>" },
         { binding = "SERVICES", id = "<insert>", preview_id = "<insert>" }
]

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"

[build]
upload.format = "service-worker"
command = "npm run build"