name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'examples/**'
      - 'insomnia.json'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'examples/**'
      - 'insomnia.json'

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodejs }}

      - name: Start services
        run: |
          docker-compose up -d
          ./scripts/wait-for-healthy-container.sh postgres 30

      - name: (env) cache
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: npm ci --prefer-offline --no-audit

      - name: Run Tests
        run: npm run cov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compiles
        run: npm run build

      - name: Clean services
        if: always()
        run: docker-compose down
