name: CI

on:
  push:
    paths:
      - '!**.md'
      - '!*.md'
    branches:
      - '**'
    tags-ignore:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: changeme
        ports:
          - 5440:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        nodejs: [14]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodejs }}

    - name: (env) cache
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install
      run: npm install

    - name: Run Tests
      run: |
        export DATABASE_URL="postgresql://postgres:changeme@localhost:5440/graphql-registry?schema=public"
        npm test

    - name: Check Types
      run: npm run types

    - name: Compiles
      run: npm run build
