name: Deploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason for the release'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: (env) pnpm
        run: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm

      - name: (env) cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.nodejs }}-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.nodejs }}-

      - name: Install
        run: pnpm install

      - name: Run Tests
        run: pnpm test

      - name: Check Types
        run: pnpm run types

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}